### ISSUE TITLE
Torque on Revert to Launch

### ISSUE THREAD

**Issue by stratochief66** [MarkusA380/PersistentRotation#1]
Reproduction:
Lose control of your craft during ascent due to aerodynamic forces. Revert to Launch. The craft & clamps will still bear the angular momentum they were experiencing during launch failure before the revert.

Solution (?):
Dump angular momentum memory for the active craft when Revert to Launch is used.

**Comment by markusa380** [comment]
Will work on it.  Thank you for the detailed feedback.  :)

**Comment by stratochief66** [comment]
No problem at all, thanks for the excellent mod!

**Comment by markusa380** [comment]
Fixed. Enjoy! :)
