### ISSUE TITLE
Exception: The given key was not present in the dictionary

### ISSUE THREAD

**Issue by Galenmacil** [MarkusA380/PersistentRotation#10]
Log excerpt:

[EXC 23:02:52.929] KeyNotFoundException: The given key was not present in the dictionary.
    System.Collections.Generic.Dictionary`2[System.String,ITargetable].get_Item (System.String key)
    PersistentRotation.Main.FixedUpdate ()

**Comment by markusa380** [comment]
Possibly fixed in 1.2.
