### ISSUE TITLE
Throttle Controlled Avionics compatibility

### ISSUE THREAD

**Issue by dtrauma** [MarkusA380/PersistentRotation#17]
Hey,
it would be nice if PR could recognize the TCA autopilot as well as those from the other mods you support.

TCA: http://forum.kerbalspaceprogram.com/index.php?/topic/97154-122-throttle-controlled-avionics/

**Comment by dtrauma** [comment]
Corresponding issue in TCA

https://github.com/qfeys/ThrottleControlledAvionics/issues/39

**Comment by markusa380** [comment]
I don't see why it shouldn't.

**Comment by markusa380** [comment]
Huh, was fixed by TCA dev already.
