### ISSUE TITLE
Rotation Persists Across Saves

### ISSUE THREAD

**Issue by CultistO** [MarkusA380/PersistentRotation#2]
Reproduction:
Put a craft in orbit with a lot of rotational authority
Cancel any spin
Quick save (F5)
Get it spinning
Reload the Quick save (Hold F9)

The craft will retain the angular momentum it gained between saving and reloading.

This issue also makes it difficult to back up saves, as you have to exit the game and manually back up and track the rotation files every time.

Potential Solution?:
Store rotation in the save file any time the game is saved, and collect it again any time the game is reloaded.

**Comment by markusa380** [comment]
Fixed with 1.0.2. Thanks for the feedback.
